name: CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & test - ${{ matrix.os }} - ${{ matrix.python-version }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-11", "macos-12" ]
        python-version: [ "3.9", "3.10" ]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install

      - name: Build the project
        run: |
          ./build.sh

      - name: Run tests
        run: |
          poetry run pytest tests/c_bindings_test.py
